# Use a imagem base do Ubuntu
FROM ubuntu:latest

# Atualize o sistema e instale o BIND9
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y bind9 && \
    rm -rf /var/lib/apt/lists/*

# Copie o arquivo de configuração do BIND e o script de inicialização
COPY named.conf.options /etc/bind/

# Exponha a porta 53 para tráfego DNS
EXPOSE 53/tcp
EXPOSE 53/udp

# Execute o script de inicialização quando o contêiner for iniciado
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
